CREATE SCHEMA IF NOT EXISTS DB2RTC AUTHORIZATION sa;

CREATE TABLE DB2RTC.FTR_PDA_MGCT (
	CD_FTR_PDA_MGCT INTEGER NOT NULL,
	CD_TIP_MC_PDA_MGCT SMALLINT NOT NULL,
	NM_FTR_PDA_MGCT CHAR(60) NOT NULL,
	TX_DCR_FTR_PDA CHAR(200) NOT NULL,
	IN_ATVC_FTR_PDA CHAR(1) NOT NULL,
	CD_USU_RSP_ULT_ATL CHAR(8) NOT NULL,
	TS_ULT_ATL_FTR_PDA TIMESTAMP NOT NULL,
	CONSTRAINT FTR_PDA_MGCT_PK PRIMARY KEY (CD_FTR_PDA_MGCT)
);

CREATE TABLE DB2RTC.EVT_PDA_MGCT (
	CD_EVT_PDA_MGCT INTEGER NOT NULL,
	CD_TIP_MC_PDA_MGCT SMALLINT NOT NULL,
	NM_EVT_PDA_MGCT CHAR(60) NOT NULL,
	TX_DCR_EVT_PDA CHAR(200) NOT NULL,
	IN_ATVC_EVT_PDA CHAR(1) NOT NULL,
	CD_USU_RSP_ULT_ATL CHAR(8) NOT NULL,
	TS_ULT_ATL_EVT_PDA TIMESTAMP NOT NULL,
	CONSTRAINT EVT_PDA_MGCT_PK PRIMARY KEY (CD_EVT_PDA_MGCT)
);

CREATE TABLE DB2RTC.NVL_IDCO_PDA_CLI (
	CD_PSS INTEGER NOT NULL,
	CD_CAS_PDA_MGCT INTEGER NOT NULL,
	CD_IDCO_PDA_CLI INTEGER NOT NULL,
	NR_ORD_NVL_IDCO SMALLINT NOT NULL,
	NM_NVL_IDCO_PDA CHAR(10) NOT NULL,
	CD_TIP_MC_PDA_MGCT SMALLINT NOT NULL,
	DT_PRCT DATE,
	CONSTRAINT NVL_IDCO_PDA_CLI_PK PRIMARY KEY (CD_PSS,CD_CAS_PDA_MGCT,CD_IDCO_PDA_CLI)
);

INSERT INTO DB2RTC.EVT_PDA_MGCT (CD_EVT_PDA_MGCT,CD_TIP_MC_PDA_MGCT,NM_EVT_PDA_MGCT,TX_DCR_EVT_PDA,IN_ATVC_EVT_PDA,CD_USU_RSP_ULT_ATL,TS_ULT_ATL_EVT_PDA)
VALUES (4,2,'.','SEM EVENTO IDENTIFICADO ','S','F6770388','2015-08-05 10:59:53.000');
INSERT INTO DB2RTC.EVT_PDA_MGCT (CD_EVT_PDA_MGCT,CD_TIP_MC_PDA_MGCT,NM_EVT_PDA_MGCT,TX_DCR_EVT_PDA,IN_ATVC_EVT_PDA,CD_USU_RSP_ULT_ATL,TS_ULT_ATL_EVT_PDA)
VALUES (10,2,'Redução qtde lançamentos crédito em cc (últimos 12m) ','REDUçãO DA QUANTIDADE DE LANçAMENTOS DE CRéDITO EM CONTA CORRENTE, NOS úLTIMOS 12 MESES                                                                                                                 ','S','F6770388','2015-09-22 18:11:10.000');
INSERT INTO DB2RTC.EVT_PDA_MGCT (CD_EVT_PDA_MGCT,CD_TIP_MC_PDA_MGCT,NM_EVT_PDA_MGCT,TX_DCR_EVT_PDA,IN_ATVC_EVT_PDA,CD_USU_RSP_ULT_ATL,TS_ULT_ATL_EVT_PDA)
VALUES (11,2,'Redução qtde lançamentos débito em cc (últimos 12m) ','REDUçãO DA QUANTIDADE DE LANçAMENTOS DE DéBITO EM CONTA CORRENTE, NOS úLTIMOS 12 MESES                                                                                                                  ','S','F6770388','2015-09-22 18:09:59.000');
INSERT INTO	DB2RTC.EVT_PDA_MGCT (CD_EVT_PDA_MGCT, CD_TIP_MC_PDA_MGCT, NM_EVT_PDA_MGCT, TX_DCR_EVT_PDA, IN_ATVC_EVT_PDA, CD_USU_RSP_ULT_ATL, TS_ULT_ATL_EVT_PDA)
VALUES (41, 2, 'Redução volume em aplicação financeira (últimos 12m)', 'REDUçãO DO VOLUME EM APLICAçõES FINANCEIRAS, NOS úLTIMOS 12 MESES', 'S', 'F6770388', '2015-09-22 18:28:14.000');


INSERT INTO DB2RTC.FTR_PDA_MGCT (CD_FTR_PDA_MGCT,CD_TIP_MC_PDA_MGCT,NM_FTR_PDA_MGCT,TX_DCR_FTR_PDA,IN_ATVC_FTR_PDA,CD_USU_RSP_ULT_ATL,TS_ULT_ATL_FTR_PDA)
VALUES (10,2,'.','SEM FATOR IDENTIFICADO','S','F6770388','2015-08-05 11:00:27.000');
INSERT INTO DB2RTC.FTR_PDA_MGCT (CD_FTR_PDA_MGCT,CD_TIP_MC_PDA_MGCT,NM_FTR_PDA_MGCT,TX_DCR_FTR_PDA,IN_ATVC_FTR_PDA,CD_USU_RSP_ULT_ATL,TS_ULT_ATL_FTR_PDA)
VALUES (11,2,'Aumento qtde instituições financeiras (últimos 12m)','AUMENTO DA QUANTIDADE DE INSTITUIçõES FINANCEIRAS DO CLIENTE, NOS úLTIMOS 12 MESES','S','F6770388','2015-09-22 18:36:35.000');
INSERT INTO	DB2RTC.FTR_PDA_MGCT (CD_FTR_PDA_MGCT, CD_TIP_MC_PDA_MGCT, NM_FTR_PDA_MGCT, TX_DCR_FTR_PDA, IN_ATVC_FTR_PDA, CD_USU_RSP_ULT_ATL, TS_ULT_ATL_FTR_PDA)
VALUES (41, 2, 'Reclamação por relacionamento (últimos 6m)', 'OCORRêNCIA DE RECLAMAçãO POR RELACIONAMENTO, NOS úLTIMOS 6 MESES', 'S', 'F6770388', '2015-09-22 18:46:35.000');

INSERT INTO DB2RTC.NVL_IDCO_PDA_CLI (CD_PSS,CD_CAS_PDA_MGCT,CD_IDCO_PDA_CLI,NR_ORD_NVL_IDCO,NM_NVL_IDCO_PDA,CD_TIP_MC_PDA_MGCT,DT_PRCT)
VALUES (355,1,41,25,'Redução vo',2,'2017-12-16');
INSERT INTO DB2RTC.NVL_IDCO_PDA_CLI (CD_PSS,CD_CAS_PDA_MGCT,CD_IDCO_PDA_CLI,NR_ORD_NVL_IDCO,NM_NVL_IDCO_PDA,CD_TIP_MC_PDA_MGCT,DT_PRCT)
VALUES (355,1,11,38,'Redução qt',2,'2017-12-16');
INSERT INTO DB2RTC.NVL_IDCO_PDA_CLI (CD_PSS,CD_CAS_PDA_MGCT,CD_IDCO_PDA_CLI,NR_ORD_NVL_IDCO,NM_NVL_IDCO_PDA,CD_TIP_MC_PDA_MGCT,DT_PRCT)
VALUES (355,2,10,9999,'.',2,'2017-12-16');
INSERT INTO DB2RTC.NVL_IDCO_PDA_CLI (CD_PSS,CD_CAS_PDA_MGCT,CD_IDCO_PDA_CLI,NR_ORD_NVL_IDCO,NM_NVL_IDCO_PDA,CD_TIP_MC_PDA_MGCT,DT_PRCT)
VALUES (355,1,4,9999,'.',2,'2017-12-16');



